export {default as login} from './acl/login'
export {default as user} from './acl/user'
export {default as role} from './acl/role'
export {default as menu} from './acl/menu'
export {default as category} from './category'
export {default as clientUser} from './clientUser'
export {default as order} from './order'
export {default as trademark} from './product/trademark'//新添加的
export {default as attr} from './product/attr'//新添加的
export {default as spu} from './product/spu'//新添加的
export {default as sku} from './product/sku'//新添加的
